### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by pzaj2** [Inconcessus/OTMapGen#12]
When generating a map with following configuration:

```yaml
  SEED: "",
  WIDTH: 10000,
  HEIGHT: 10000,
  VERSION: "10.98",
  TERRAIN_ONLY: false,
  GENERATION: {
    NOISE_INCREMENT: 14,
    ISLAND_DISTANCE_DECREMENT: 0.42,
    ISLAND_DISTANCE_EXPONENT: 0.45,
    CAVE_DEPTH: 20,
    CAVE_ROUGHNESS: 0.45,
    CAVE_CHANCE: 0.5,
    SAND_BIOME: true,
    EUCLIDEAN: false,
    SMOOTH_COASTLINE: true,
    ADD_CAVES: true,
    WATER_LEVEL: 2,
    EXPONENT: 1.4,
    LINEAR: 4,
    MOUNTAIN_TYPE: "MOUNTAIN",
    FREQUENCIES: [
      { f: 1, weight: 0.3 },
      { f: 2, weight: 0.4 },
      { f: 4, weight: 0.4 },
      { f: 8, weight: 0.225 },
      { f: 16, weight: 0.23 },
      { f: 32, weight: 0.11 },
      { f: 64, weight: 0.0025 },
    ],
  },
``` 

i7 11th gen, 32GB RAM just FYI
